# Generated by Django 5.2.4 on 2025-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default/profile.png', null=True, upload_to='profiles/'),
        ),
    ]
